### ISSUE TITLE
./setup 에러

### ISSUE THREAD

**Issue by wook8321** [KNU-2022S-OSP-03-09/project#7]
ERROR: Command errored out with exit status 1:
   command: /home/wook8321/project/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5d60jcix/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5d60jcix/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3gxzsfh3
       cwd: /tmp/pip-install-5d60jcix/psycopg2/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for psycopg2
  Running setup.py clean for psycopg2
  Building wheel for kaitaistruct (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/wook8321/project/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5d60jcix/kaitaistruct/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5d60jcix/kaitaistruct/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xyvd38be
       cwd: /tmp/pip-install-5d60jcix/kaitaistruct/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for kaitaistruct
  Running setup.py clean for kaitaistruct
  Building wheel for blinker (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/wook8321/project/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5d60jcix/blinker/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5d60jcix/blinker/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-tw0_bssd
       cwd: /tmp/pip-install-5d60jcix/blinker/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for blinker
  Running setup.py clean for blinker
Failed to build psycopg2 kaitaistruct blinker
ERROR: selenium-wire 4.6.4 has requirement werkzeug==2.0.3, but you'll have werkzeug 2.1.2 which is incompatible.
Installing collected packages: wheel, six, pytz, backports.zoneinfo, tzdata, pytz-deprecation-shim, tzlocal, apscheduler, Werkzeug, zipp, importlib-metadata, itsdangerous, click, MarkupSafe, Jinja2, flask, psycopg2, sortedcontainers, idna, attrs, sniffio, async-generator, outcome, trio, h11, wsproto, trio-websocket, pycparser, cffi, cryptography, pyOpenSSL, certifi, pysocks, urllib3, selenium, pyparsing, hyperframe, hpack, h2, pyasn1, kaitaistruct, zstandard, brotli, blinker, selenium-wire, greenlet, sqlalchemy
    Running setup.py install for psycopg2 ... error
    ERROR: Command errored out with exit status 1:
     command: /home/wook8321/project/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5d60jcix/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5d60jcix/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-eglaozcw/install-record.txt --single-version-externally-managed --compile --install-headers /home/wook8321/project/venv/include/site/python3.8/psycopg2
         cwd: /tmp/pip-install-5d60jcix/psycopg2/
    Complete output (38 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/psycopg2
    copying lib/__init__.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/_range.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/sql.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/_ipaddress.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/pool.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/_json.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/tz.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/extras.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/errors.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/errorcodes.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/extensions.py -> build/lib.linux-x86_64-3.8/psycopg2
    running build_ext
    building 'psycopg2._psycopg' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/psycopg
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSYCOPG_VERSION=2.9.3 (dt dec pq3 ext lo64) -DPSYCOPG_DEBUG=1 -DPG_VERSION_NUM=120011 -DHAVE_LO64=1 -DPSYCOPG_DEBUG=1 -I/home/wook8321/project/venv/include -I/usr/include/python3.8 -I. -I/usr/include/postgresql -I/usr/include/postgresql/12/server -I/usr/include/libxml2 -I/usr/include/mit-krb5 -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-3.8/psycopg/psycopgmodule.o -Wdeclaration-after-statement
    In file included from psycopg/psycopgmodule.c:28:
    ./psycopg/psycopg.h:36:10: fatal error: libpq-fe.h: No such file or directory
       36 | #include <libpq-fe.h>
          |          ^~~~~~~~~~~~
    compilation terminated.
    
    It appears you are missing some prerequisite to build the package from source.
    
    You may install a binary package by installing 'psycopg2-binary' from PyPI.
    If you want to install psycopg2 from source, please install the packages
    required for the build and try again.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/wook8321/project/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5d60jcix/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5d60jcix/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-eglaozcw/install-record.txt --single-version-externally-managed --compile --install-headers /home/wook8321/project/venv/include/site/python3.8/psycopg2 Check the logs for full command output.

**Comment by tipifv** [comment]
7bf193d3e0963ea51b29c146cfcd29a4da8e2079
